---
title: "housing"
author: "Razmig Zeitounian"
date: "7/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)

df <- read_csv("housePrices/kc_house_data.csv")

#drop id and date col since we wont use those
df <- df %>% 
  select(-c(id, date))

#add a column to define perceived age, which we will say is year built/renovated using function

perceived_age <- function(built = df$yr_built, renovated = df$yr_renovated){
  if(renovated == 0){
    return(2020-built)
  } else {
  new_age = renovated - built  
  return(new_age)
  }
}

#now drop yr built and renovated since we have a better variable to use for comparison
df <- cbind(df, perceived_age()) %>% 
  select(-c(yr_built, yr_renovated))

glimpse(df)
```

```{r}
p <- ggplot(df, aes(price)) + 
  geom_histogram(col = "black", fill = "pink") +
  ylab("Count") +
  ggtitle("Distribution of Housing Prices in King County")

#get rid of scientific notation in x axis
p + scale_x_continuous(labels = function(x) format(x, scientific = FALSE)) 
```


